language: python
services:
- rabbitmq
- mysql
python:
- 2.7
- 3.6

env:
- MYSQL_ENV_MYSQL_USER=travis
- MYSQL_ENV_MYSQL_PASSWORD=

stages:
- lint
- test

before_script:
- pushd travis/archive; ArchiveInterfaceServer.py --config config.cfg & popd
- pushd travis/cartd; CartServer.py & celery -A cart worker -l info -P solo & popd
- python test_files/archiveinterfacepreload.py
script:
- coverage run --include='pacifica/*' -m pytest -v
- coverage report -m --fail-under 100
- if [[ $CODECLIMATE_REPO_TOKEN ]] ; then codeclimate-test-reporter; fi

jobs:
  include:
  - stage: lint
    python: 3.6
    script: pre-commit run -a
  - python: 2.7
    script: pre-commit run -a

install:
- pip install -r requirements-dev.txt
