version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true

environment:
  matrix:
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python36-x64

install:
  - ps: >
      & "$env:PYTHON\python.exe" -m virtualenv C:\pacifica;
      C:\pacifica\Scripts\activate.ps1;
      python -m pip install --upgrade pip setuptools wheel;
      python -m pip install -r requirements-dev.txt

build: off

test_script:
  - ps: >
      mkdir C:\tmp; C:\pacifica\Scripts\activate.ps1;
      pre-commit run -a;
      $ai_proc = Start-Process C:\pacifica\Scripts\python.exe -ArgumentList "C:\pacifica\Scripts\ArchiveInterfaceServer.py --config config.cfg" -WorkingDirectory 'travis\archive' -PassThru -RedirectStandardError celery-error.log -RedirectStandardOutput celery-output.log;
      $env:ARCHIVEI_PORT_8080_TCP_ADDR = '127.0.0.1';
      $back_proc = Start-Process C:\pacifica\Scripts\celery.exe -ArgumentList "-A cart worker -l info -P eventlet" -WorkingDirectory 'travis\cartd' -PassThru -RedirectStandardError celery-error.log -RedirectStandardOutput celery-output.log;
      $front_proc = Start-Process C:\pacifica\Scripts\CartServer.exe -ArgumentList "--stop-after-a-moment" -WorkingDirectory 'travis\cartd' -PassThru -RedirectStandardError server-error.log -RedirectStandardOutput server-output.log;
      python test_files\archiveinterfacepreload.py;
      coverage run --include='pacifica/*' -m pytest -v;
      celery -A cart control shutdown;
      $front_proc | Wait-Process;
      coverage report -m --fail-under=100;
